#!/bin/sh

#cd ../bin
#silgystop
#cd ../src

echo Making silgy_app...

g++ silgy_app.cpp \
../lib/silgy_eng.c ../lib/silgy_lib.c ../lib/silgy_usr.c \
-s -O3 \
-I. -I../lib \
-lrt \
-o ../bin/silgy_app

echo Making silgy_svc...

g++ silgy_svc.cpp \
../lib/silgy_eng.c ../lib/silgy_lib.c ../lib/silgy_usr.c \
-s -O3 \
-D SILGY_SVC \
-I. -I../lib \
-lrt \
-o ../bin/silgy_svc

#cd ../bin
#silgystart
#cd ../src
